#!/bin/bash
#
# aaPanel Provisioning Script
# Installs aaPanel (English version) with SSL enabled
#
# Required env vars:
#   DOMAIN          - Hostname for the server (e.g. panel.example.com) — injected by agent
#
# Optional env vars:
#   PANEL_PORT      - Panel port (default: 8888)
#   PANEL_USER      - Admin username (default: auto-generated by aaPanel)
#   PANEL_PASS      - Admin password (default: auto-generated by aaPanel)
#
# Supports: Ubuntu 22/24, Debian 11/12, AlmaLinux 8/9, Rocky Linux 8/9, CentOS 7/8/9

set -euo pipefail

# ─── Force non-interactive mode ──────────────────────────────────────────────
export DEBIAN_FRONTEND=noninteractive
APT_OPTS=(-y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold")

# ─── Variables ───────────────────────────────────────────────────────────────

DOMAIN="${DOMAIN:?DOMAIN env var is required}"
PANEL_PORT="${PANEL_PORT:-8888}"
PANEL_USER="${PANEL_USER:-}"
PANEL_PASS="${PANEL_PASS:-}"
CREDS_FILE="/root/.aapanel-credentials"
INSTALL_SCRIPT_URL="https://www.aapanel.com/script/install_panel_en.sh"

echo "=========================================="
echo "  aaPanel Provisioner"
echo "  Hostname : ${DOMAIN}"
echo "  Port     : ${PANEL_PORT}"
echo "=========================================="

# ─── Wait for package manager lock ──────────────────────────────────────────

wait_for_package_manager() {
    local max_wait=300
    local waited=0

    if command -v apt-get &>/dev/null; then
        echo "==> Waiting for apt lock to be released..."
        while fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock &>/dev/null 2>&1; do
            if [ "${waited}" -ge "${max_wait}" ]; then
                echo "ERROR: Timed out waiting for apt lock after ${max_wait}s"
                exit 1
            fi
            sleep 2
            waited=$((waited + 2))
        done
    elif command -v dnf &>/dev/null || command -v yum &>/dev/null; then
        echo "==> Waiting for yum/dnf lock to be released..."
        while fuser /var/run/yum.pid /var/run/dnf.pid &>/dev/null 2>&1; do
            if [ "${waited}" -ge "${max_wait}" ]; then
                echo "ERROR: Timed out waiting for yum/dnf lock after ${max_wait}s"
                exit 1
            fi
            sleep 2
            waited=$((waited + 2))
        done
    fi

    if [ "${waited}" -gt 0 ]; then
        echo "==> Package manager lock released after ${waited}s"
    fi
}

# ─── Detect OS ───────────────────────────────────────────────────────────────

detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS_ID="${ID}"
        OS_VERSION="${VERSION_ID}"
    else
        echo "ERROR: Cannot detect OS (no /etc/os-release)"
        exit 1
    fi

    # Determine package manager
    if command -v apt-get &>/dev/null; then
        PKG_MANAGER="apt"
    elif command -v dnf &>/dev/null; then
        PKG_MANAGER="dnf"
    elif command -v yum &>/dev/null; then
        PKG_MANAGER="yum"
    else
        echo "ERROR: No supported package manager found"
        exit 1
    fi

    echo "==> Detected: ${OS_ID} ${OS_VERSION} (${PKG_MANAGER})"
}

# ─── Prerequisites ───────────────────────────────────────────────────────────

install_prerequisites() {
    wait_for_package_manager

    if [ "${PKG_MANAGER}" = "apt" ]; then
        dpkg --configure -a --force-confdef --force-confold || true
        apt-get update -y
        apt-get install "${APT_OPTS[@]}" curl wget cron
    else
        ${PKG_MANAGER} install -y curl wget cronie
    fi

    echo "==> Prerequisites installed"
}

# ─── Install aaPanel ─────────────────────────────────────────────────────────

install_aapanel() {
    echo "==> Downloading aaPanel installer..."
    cd /tmp
    curl -ksSO "${INSTALL_SCRIPT_URL}"

    echo "==> Running aaPanel installer (non-interactive)..."

    # Build install command with options
    local install_cmd="bash install_panel_en.sh ipssl -y -P ${PANEL_PORT}"

    if [ -n "${PANEL_USER}" ]; then
        install_cmd="${install_cmd} -u ${PANEL_USER}"
    fi
    if [ -n "${PANEL_PASS}" ]; then
        install_cmd="${install_cmd} -p ${PANEL_PASS}"
    fi

    # Run installer — aaPanel installer uses its own set -e, so we allow it to manage errors
    eval "${install_cmd}" || {
        echo "ERROR: aaPanel installation failed"
        exit 1
    }

    echo "==> aaPanel installation completed"
}

# ─── Open Firewall Ports ────────────────────────────────────────────────────

configure_firewall() {
    echo "==> Configuring firewall"

    if command -v ufw &>/dev/null; then
        ufw allow "${PANEL_PORT}"/tcp || true
        ufw allow 80/tcp || true
        ufw allow 443/tcp || true
        ufw allow 20/tcp || true
        ufw allow 21/tcp || true
        ufw allow 888/tcp || true
        ufw allow 39000:40000/tcp || true
        echo "y" | ufw enable || true
    elif command -v firewall-cmd &>/dev/null; then
        firewall-cmd --permanent --add-port="${PANEL_PORT}"/tcp || true
        firewall-cmd --permanent --add-port=80/tcp || true
        firewall-cmd --permanent --add-port=443/tcp || true
        firewall-cmd --permanent --add-port=20/tcp || true
        firewall-cmd --permanent --add-port=21/tcp || true
        firewall-cmd --permanent --add-port=888/tcp || true
        firewall-cmd --permanent --add-port=39000-40000/tcp || true
        firewall-cmd --reload || true
    fi

    echo "==> Firewall configured"
}

# ─── Save Credentials ───────────────────────────────────────────────────────

save_credentials() {
    local server_ip
    server_ip=$(hostname -I | awk '{print $1}')

    # Extract aaPanel credentials from its own files
    local panel_user=""
    local panel_pass=""
    local panel_path=""

    # aaPanel stores credentials in these locations
    if [ -f /www/server/panel/data/default.db ]; then
        panel_user=$(cd /www/server/panel && python3 -c "
import sqlite3
conn = sqlite3.connect('data/default.db')
cursor = conn.cursor()
cursor.execute('SELECT username FROM users LIMIT 1')
row = cursor.fetchone()
print(row[0] if row else 'admin')
conn.close()
" 2>/dev/null || echo "check panel")
    fi

    if [ -f /www/server/panel/default.pl ]; then
        panel_pass=$(cat /www/server/panel/default.pl 2>/dev/null || echo "check panel")
    fi

    # Get safe entry path
    if [ -f /www/server/panel/data/admin_path.pl ]; then
        panel_path=$(cat /www/server/panel/data/admin_path.pl 2>/dev/null || echo "")
    fi

    cat > "${CREDS_FILE}" <<EOF
==========================================
  aaPanel Installation Complete
  Created: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
==========================================

  Panel Access:
    URL      : https://${server_ip}:${PANEL_PORT}${panel_path}
    Username : ${panel_user}
    Password : ${panel_pass}

  Domain   : ${DOMAIN}
  Server IP: ${server_ip}
  Port     : ${PANEL_PORT}

  First Steps:
    1. Log into panel at https://${server_ip}:${PANEL_PORT}${panel_path}
    2. Choose your web stack (LNMP or LAMP)
    3. Add your website domain
    4. Configure SSL certificate

==========================================
EOF

    chmod 600 "${CREDS_FILE}"
    echo "==> Credentials saved to ${CREDS_FILE}"
}

# ─── Welcome Screen (MOTD) ──────────────────────────────────────────────────

setup_motd() {
    echo "==> Setting up SSH welcome screen"

    # Disable default MOTD components
    chmod -x /etc/update-motd.d/* 2>/dev/null || true

    cat > /etc/update-motd.d/99-app-info <<'MOTD_SCRIPT'
#!/bin/bash
CREDS_FILE="/root/.aapanel-credentials"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    aaPanel SERVER                           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
if [ -f "${CREDS_FILE}" ]; then
    cat "${CREDS_FILE}"
else
    echo "  Credentials file not found: ${CREDS_FILE}"
fi
echo ""
echo "  Useful Commands:"
echo "  ─────────────────────────────────────────────"
echo "  bt                             aaPanel CLI menu"
echo "  bt default                     Show panel info"
echo "  bt restart                     Restart panel"
echo "  cat /root/.aapanel-credentials View credentials"
echo ""
MOTD_SCRIPT

    chmod +x /etc/update-motd.d/99-app-info
    echo "==> MOTD configured"
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
    detect_os
    install_prerequisites
    install_aapanel
    configure_firewall
    save_credentials
    setup_motd

    echo ""
    cat "${CREDS_FILE}"
}

main
